---
title: "Examining the Impact of Covid-Shutdown on Toronto Restaurants Paper"
author: "Youjing Li, Ken Lee, Renjing Liu, Jialin Zhao"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: ""
output: 
  bookdown::pdf_document2:
    toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Introduction
Local businesses, especially restaurants, are the soul of many cities, providing not just a source of food, but also culinary diversity, culture, and employment for the population. In fact, these restaurants are vital contributors to the local community, donating to food banks, hosting fundraisers, and much more. Hence, with the presence of COVID-19, it is clear why the Ontario government would want to understand more about the potential effects a shutdown could have on the restaurants. Nevertheless, limiting the spread of this virus should be a top priority, but shutting down restaurants could have an immense effect on the local community, and hence affect the livelihoods of many Ontario residents. After all, many other factors have already had an adverse impact on the restaurant industry. For instance, studies like the “COVID-19 and restaurant demand: Early effects of the pandemic and stay-at-home orders” [@citeLit1] have shown that a 1% increase in new COVID cases results in 0.0556% of daily restaurant demand, while stay-at-home orders have been associated with a decrease of 3.30% in restaurant demand.

Therefore, this paper will focus on examining the effects of COVID shutdowns on restaurants, taking into account factors such as the net profit/loss of the businesses, the permanent closure of the restaurant, number of employees, wages, and food price. After all, shutting down a restaurant does not just affect the restaurant owners, as people may lose their jobs, have their wage/salary decrease, and prices for food may increase to compensate for losses.

For this research, we will first describe the intervention of this experiment where randomized controlled trial testing will be conducted on a sample of the restaurant population in Ontario. The methodology involved will then be defined, illustrating how we will be observing the restaurants, what will be measured, the population and sample of the experiment, and the predicted cost of gathering the data. At last, upon denoting all the details of our experiment’s intervention method and survey methodology, we will be exploring our findings of the effects of COVID shutdowns on restaurants in the discussion section. All in all, this study will highlight the potential losses in profits and employment caused by restaurant shutdowns, helping Ontario government officials make better-informed decisions regarding the COVID restrictions such as shutdowns.

\newpage

# Data

## Intervention

## Survey

### Methodology
The survey is generated using Google Form and is set to only one response per user to avoid duplicate responses. In addition, the survey includes an explanation of the experiment, denoting how the experiment will be conducted and upcoming surveys that they would still need to fill out in the following two months. For instance, it would explain how they would be allowed to operate normally in the first month, but some may be randomly picked to be shut-down in the second month. Of course, it would also indicate the compensation that would be given to them for shutting down (while also specifying that the compensation would not form part of the restaurant’s revenue as to not intervene with the experiment). Additionally, we will be assuring the participants that their data would ultimately be anonymous and stored safely for their privacy, ensuring there are no privacy concerns and increasing the response rate.  After all, the research data we collect from responsive surveys will fall under the Municipal Freedom of Information and Protection of Privacy Act[@citeLit6]. Personal information such as the respondent’s location, or opinions will be encoded into different classifications to hide sensitive personal information, and also the survey will be conducted anonymously to ensure all information is handled in a de-identified manner. The information we collect, use and analyze will not disclose to any third-party and only for research-purpose which comply with privacy protection provisions of the Acts. At last, the survey explanation would also include the importance of this study as it could inform government plans regarding how restaurants’ laws are imposed. This would encourage respondents to answer the surveys, reducing the non responses. Of course, we made sure to state that their responses would not directly affect, but just inform government decisions, as some respondents may want to answer dishonestly to affect potential governmental outcomes.

More specifically, since we obtain detailed information for these 380 selected sample restaurants, such as email and phone number through Yelp API, the survey will first be conducted through an email survey, where we attach and send the survey link to associated email contact manually and respondents would be given a chance to opt-out of the study, preventing further contact from us. Nevertheless, upon a non-response, a similar follow-up email survey will be sent to reduce non-responses. Again, this survey would give the respondent a second chance to opt-out of this study. At last, if the emails garner no responses, a final phone call survey would be implemented to further reduce non-responses. These email and phone surveys will help us obtain information about each restaurant in these two control and treatment groups after performing the stratified sampling technique for the target population. The survey methodology process would be repeated three times, before the first month to provide the purpose of the experiment and options to opt-out/opt-int, at the end of the first month to have an idea (benchmark) of their usual performance, and at the end of the final month to evaluate the performance of the restaurants after treating half of them with lockdowns. Additionally, respondents will also be informed in the first survey that they will be rewarded after completing all three surveys with an incentive(such as Amazon gift cards) in order to achieve a higher response rate (a track record of the responses would be used to make sure restaurants do not send in two surveys and receive more than one gift card). If any of the restaurants that participated in the first survey decide not to participate in the upcoming surveys, they will not be able to obtain a gift card, and their previous data points in the past survey would be omitted. In fact, since we could not guarantee each respondent will take the survey eventually, weight-class adjustments will be implemented by increasing the sampling weights of respondents to manage the variation caused by unit nonresponses, in order to help us deal with non-response bias which could affect the validity of the research analysis and lead to an underestimation or overestimation of the true outcome.


The construction of the survey itself will be free with the Google Form platform and we will conduct the survey through email and phone only in which there will be no cost for sending email survey but an extra expense of calling non-response participants is required. Since the survey will be implemented in April and May, a two-month prepaid phone plan from Koodo mobile which is 25 CAD($) per month with unlimited province-wide calling will be purchased. In addition, each respondent will be rewarded with a 10 $ Amazon gift card after completing all three surveys and the selected sample group for the survey is around 380. The estimated cost of conducting the survey is about 3850 $ where 3800 $ will be used for purchasing Amazon gift cards(10 $ gift card for each respondent), and 50 $ is the payment for a two-month prepaid phone plan(25 $ per month). 

\newpage

### Dataset

\newpage

# Discussion

\newpage

# References
